# netlify.toml
[build]
  publish = "."
  command = ""  # مشروع ستاتيكي، لا حاجة لأمر بناء

# دعم التوجيه للروابط العميقة (SPA/عدة صفحات ستاتيكية)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
